language: scala
sudo: required

jdk:
  - oraclejdk8

env:
  global:
  - TRAVIS_NODE_VERSION="8"

matrix:
  include:
  - env: TRAVIS_SBT_VERSION="0.13.15"
  - env: TRAVIS_SBT_VERSION="1.0.2"

before_install:
  - nvm install 6
  - nvm use 6
  - node --version

script:
  - sbt -no-colors ";^^$TRAVIS_SBT_VERSION;test;it:test;runScripted"

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
