language: scala
sudo: false
jdk:
- oraclejdk8
env:
  global:
  - TRAVIS_NODE_VERSION="8"
  - TRAVIS_SBT_VERSION="1.2.8"
  - secure: mNYTA9y/VA5dhG4Ukg24uRfYEC/s5kMEJKaVg9YdikA9Kad8GlxUVuCmg49BJjGen446NqM9DgrF9/+UTyUkywyC5vqCA+ILI9J3POvkiOhy5A99Ymip5VrYdJEBqTr3SszxkFtZ0nSR8xxN6ypiQ/DDCUMHyYweeX4ZruTcOZKMnTXD9fw/q4WHxL/leO5mSbEVYDh5nhMOxg9etmtezTfW6VRUfe1D7t7odIkIViDuhzIxqHx1J1CqWTC52x6DzbOiEeBrl1ZLl3r+weQA8HtxjTtqC+HutsrsRGwS/0ew+A9jOuOcHSoNIiC1JbSEvTFkvin1jwNqDjj8WPu2vZvGVSukvFQtaH2I5SEBPKBnteoV/4TSGvU6aZ4WdaJIULg3gXeoOSLxzC5WEyqYMBiWWtH3VkAQy6+CknD+TfKuBU0u2EsXxY0ni1mTZPWldoErzPQlDMs4cIfRZ5iaSwoXvC7tLVCGHJfaOKhKwslcspaufUWZcOvgrrNjlnjqghrqQa8GDnLCXcJwal6EMH0RJqgWymZ0JdZUB61pQ9ZD2AylpCdQSUqUDq1gFQyGpN+QIWTNYgteO6zKrZMeKknDh7uCEcovFI9ZmZYoF0NtA2lPGgBg3Zeb41+MUKwVSzQG3QocVzLcHSA66ZV/F4MMzrmZ05jIp7yHxCztmzg=
  - secure: ArRCYDfNlBMAQJpRBtFedg6Bw43nvxfkh7Eec0oFUdxrO9z1zf9ezpNeyx67lnJ29E8i9eEWtaT+XE1W8KpewQJHogxq84A1PoVI84VMtzf5NAwjZBN+TV3mPbmme8rADmFAFWBD7zF5eSpNtQkDK2BUjC4uwrGVP0/0K5VhunKTBBg4jW2r+cogncLYJ9KTEpMx9HhO3hOvdnR0v8oqOptlCla6Nmnb8DjyVVbO1fg8pRW2XQ4wE012e7MHRnw0CaRge1kaj8yrRMJhdxFgrY0OdetKFS1DJ1tSeQCT8AdCXErNN8M6lGRiYELpIddEd479NsJ4QDTZ0dU2tHfWHJCakb4CfehJ0Qm6Q4NVQafIAlwLfIROV3TaoZkjS1ZuLhV0az3pdnzNGJGkLmjV41otk1DoboV4lON9rjiyO04Gj53M+ZpmsbjxDQiCU07E5fSrT6Hdnt0Z0RbLBPE/ge21UNK8WBUElD3XMtsFSPvOziJu6iUVxw+CNx1yQVu2ENEDMRKf/qdulx4H2Ee3TIXYtYqMvYnxP2NN/BVJ2cxp+YiNpnzJBl3o6rnvPoF+vTbEKBEqf4cpuITVBADHUHwHsRaSFdTAdcT3/6VhltCcYuPOHWzONlMfQZJLQhi25PTO7L8eImatFKpccPR1Aqido57AYUtzajk9m9pRDDo=
before_install:
- nvm install 6
- nvm use 6
- node --version
script:
- sbt clean coverage test coverageReport &&
  sbt coverageAggregate
after_success:
- sbt coveralls
- if [ $TRAVIS_BRANCH = 'master' ] && [[ "$(<version.sbt)" =~ (.*SNAPSHOT.*) ]]; then
    sbt clean publish;
  fi
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
